source 'https://rubygems.org/' do
  gem 'test-kitchen', '~> 2.5.0'
  gem 'kitchen-terraform', '~> 5.3.0'
  gem 'kitchen-verifier-awspec', '~> 0.2.0'
  gem 'awspec', '~> 1.18.0'
  gem 'hcl-checker'
end
